package:
  name: yeadon
  version: "1.2.1"

source:
  fn: yeadon-1.2.1.tar.gz
  url: https://pypi.python.org/packages/source/y/yeadon/yeadon-1.2.1.tar.gz
  md5: 58a5af9863d6e06d3bb342513ffd5e8f

requirements:
  build:
    - python
    - setuptools
    - numpy >=1.6.1
    - pyyaml >=3.10

  run:
    - python
    - numpy >=1.6.1
    - pyyaml >=3.10
    - mayavi >=4.0

test:
  # Python imports
  imports:
    - yeadon
    - yeadon.tests

  requires:
    - nose

about:
  home: https://github.com/chrisdembia/yeadon/
  license: LICENSE.txt
  summary: 'Estimates the inertial properties of a human.'
